### ISSUE TITLE
Add Router

### ISSUE THREAD

**Issue by Trikolon** [Endebert/squadmc#12]
Would be nice to have a router so the shown map is also reflected in the url bar. This would also enable users to use the browser navigation buttons to navigate map history.

Example:
`https://squadmc.ende.pro/#/belaya` => Belaya map is shown

**Comment by Endebert** [comment]
I don't really see the benefit of it, but i guess it could be useful. If you want it implemented, go ahead.

Regarding implementation, you would need a mapping between the path name and the map, so best approach is probably adding a `routerName` property to each map in MAPDATA.

**Comment by MumbleMurmur** [comment]
Doesn't sound very useful at all, but to each their own. :P

**Comment by ekzyis** [comment]
That sounds not too hard. Let me see if I can do it just for the sake of first time contributing on github.
:smirk:

**Comment by ekzyis** [comment]
Okay, let me see if I can finally make this happen now because of [hacktoberfest](https://hacktoberfest.digitalocean.com/) :D
