### ISSUE TITLE
New updated Post Scriptum Minimaps

### ISSUE THREAD

**Issue by beringtom** [Endebert/squadmc#16]
These are the new minimaps from playtest 2.
The files are too big for github, so they are uploaded in a zip.

https://k2s.cc/file/342570bb0a6b8/Updated_PS_minimaps.zip

**Comment by Endebert** [comment]
Awesome, thanks for the new maps. I'm currently pushing the new map files to squadmc-maps. You may have to delete your local cache for the website. Heelsum did not have any changes btw.

Oh and next please use a different hoster, like google drive, dropbox, or mega.nz. I don't really mind, as long as I get the images somehow, but they are all way faster to download from.
