### ISSUE TITLE
Great but just one question

### ISSUE THREAD

**Issue by StuartIanNaylor** [Endebert/squadmc#21]
Been using the web version and is there anyway just to type in co-ords? rather than map click?

**Comment by Endebert** [comment]
Yes there is :) This feature was added in version 2.6.0.

In the bottom right corner of the map view should be a floating "+" button. Clicking on it should pop up a dialog that lets you add/move mortar and target makers by typing in the keypad coordinates and clicking on the "+" button next to the text input field.

Clicking on the colored icons in that dialog lets you cycle through available colours.

I probably should have given the floating button a different color to make it stand out more lol.

**Comment by Endebert** [comment]
@StuartIanNaylor Based on your feedback I colored the button to make it easier to notice. I'm still trying to find an icon which implies the text input clearly, but for now, I just hope people simply try out clicking that button.

Thanks again for your feedback.
