### ISSUE TITLE
Adding other Icon

### ISSUE THREAD

**Issue by gibsonhan** [Endebert/squadmc#22]
I would like to contribute and help. I think a good thing to add is an Icon for a fob, radio, and generating the range/distance A to B is for optimal placement of stuff. Let me know what you think

**Comment by Endebert** [comment]
fob/radio makers are already implemented. You just have to disable "quick mode" in the map settings. This allows you to setup multiple fob/mortar/target markers with different colors.

Fob markers have two range circles: the smaller one is  build area, the second one is the distance until another fob can be set. I am considering showing lines between fobs similar to the lines between mortar and target, but the range circles should be sufficient for now.

If your request is specifically for PostScriptum, you would have to tell me how it works in that game, as I don't own it myself.

**Comment by Endebert** [comment]
@gibsonhan Based on your feedback I inverted the _Quick Mode_ feature and called it _Advanced Mode_, I hope this highlights these functionalities more clearly to you and other users.

Thanks again for your feedback.

**Comment by ekzyis** [comment]
>  I am considering showing lines between fobs similar to the lines between mortar and target, but the range circles should be sufficient for now.

What purpose should these lines between fobs have? I am just interested in your reasoning there.

**Comment by Endebert** [comment]
@ekzyis Well, I'm assuming the range check to other fobs in the game is happening in a sphere-like manner, i.e. height plays a role when calculating the difference between two radios. The higher the difference in height, the more inaccurate the range circles are.

Therefore I considered drawing lines between them, to display the accurate min-range they have to be away from each other. But so far I haven't bothered to add this functionality as the benefit is so small, it doesn't really outweigh the effort needed to implement it.

One could also add lines between e.g. a radio and a mortar, to see if it can be placed in building range, but the same arguments apply.
