### ISSUE TITLE
Post Scriptum new maps Doorwerth and Arnhem Range

### ISSUE THREAD

**Issue by Isoterik** [Endebert/squadmc#26]
Doorwert and Arnhem Range were added to the map pool. Arnhem Range is a training map.

[Doorwert.png](https://drive.google.com/file/d/1r4z6fSc5WABwPEFOp65ef07REItqZxct/view)

[Doorwert ingame](https://steamuserimages-a.akamaihd.net/ugc/2474053068746059085/E9D7BE478708628076FADA2A47334C430C9EA424/)

[Arnhem Range.png](https://drive.google.com/file/d/1RnXmrNf2NQNs9OoW1rto5SLuvSQrRDaj/view)

[Arnhem Range ingame](https://steamuserimages-a.akamaihd.net/ugc/2474053068748845660/48F236EA23161E9764058F91A4BAC51E13B1E42F/)

**Comment by Endebert** [comment]
Hi @Isoterik, thank you very much providing the map files and ingame screenshots. I'll try to add the new maps tomorrow.

**Comment by Endebert** [comment]
Ok, the new maps are now available. Thanks again for your help!

**Comment by Isoterik** [comment]
@Endebert thank you for providing this and your time!
