### ISSUE TITLE
Something is wrong with the site loading

### ISSUE THREAD

**Issue by Valpra** [Endebert/squadmc#36]
I'm stuck on the boot screen both in the Internet version and in the installed local version http: // localhost: 8080 /

**Comment by Trikolon** [comment]
There seems to be a certificate issue with the domain holding the map files `https://maps.squadmc.ende.pro`.
![image](https://user-images.githubusercontent.com/1077860/48829847-91ec3b00-ed73-11e8-9a41-1326074df8eb.png)
The Let's Encrypt certificate isn't served to the client. Looks like it's an issue on Netlify's side.

@Endebert

**Comment by Endebert** [comment]
Sorry for the trouble. I've contacted netlify support as they have again (now for the third time) issued a new SSL certificate only for netlify (sub-)domains, but not for ende.pro.

Please be patient. Based on my experience, it should be resolved in a couple of hours.

**Comment by Endebert** [comment]
@Valpra @Trikolon The issue should now be resolved. Sorry for the inconvenience.
