### ISSUE TITLE
New Map

### ISSUE THREAD

**Issue by tikityler** [Endebert/squadmc#39]
A new map is out called "Best" Is there any eta and is there anything I can do to help?

**Comment by Endebert** [comment]
I'm assuming this is a new map in Post Scriptum? I don't own the game, so I'm dependent on other players to provide me with:

1. the extracted map via [umodel](http://www.gildor.org/en/projects/umodel)
2. an ingame screenshot showing the whole map with the grid

Just like here: https://github.com/Endebert/squadmc/issues/26

Once I have both, it doesn't take much time to add them to the map list.

**Comment by tikityler** [comment]
Here  you are my good sir. The map name is "Best" and these are the different layers with Correct names.

![Best Single 01](https://user-images.githubusercontent.com/15217704/55320748-2444cf80-5435-11e9-81f9-d71fb37166cb.JPG)
![Best AAS 01](https://user-images.githubusercontent.com/15217704/55320831-5c4c1280-5435-11e9-96fb-8b02a457b1f7.JPG)
![Best AAS 02](https://user-images.githubusercontent.com/15217704/55320832-5c4c1280-5435-11e9-894d-324546c4ae8d.JPG)


[Best.zip](https://github.com/Endebert/squadmc/files/3028802/Best.zip)

Let me know if I missed anything you need.

**Comment by tikityler** [comment]
Also Arnhem Range has changed as far as height maps go. The actual in game map looks the same but the landscape is vastly different if that is taken into account. Here are the new files for it.
[Arnhem_Range.zip](https://github.com/Endebert/squadmc/files/3028890/Arnhem_Range.zip)
 

Suggestion that could be quite useful would be an optional X meter spread that gives you the max and min for azimuth and mills, could be useful in both squad and ps. Your current area option is awesome but takes a lot of clicking around between destination points, where as including a min and max at the bottom could speed that up. Even adding the max and min to your current area one would be a much appreciated improvement.
Its just a suggestion though, I truly appreciate your work.

Thanks again, its an awesome utility, we use SquadCalc.com only when yours is not available for a new map.

I'll make sure to get you these files as new maps come out. Would responding to this thread or making a new one each time be best?

**Comment by Endebert** [comment]
Awesome, thank you for providing all required info! I'll try to add them as soon as possible.

> Also Arnhem Range has changed as far as height maps go. The actual in game map looks the same but the landscape is vastly different if that is taken into account.

For PostScriptum, not height maps have been created unfortunately. I'd need to be able to open the maps in an SDK so I could extract them, and Post Sciptum doesn't have one if I'm not mistaken.

> Suggestion that could be quite useful would be an optional X meter spread that gives you the max and min for azimuth and mills, could be useful in both squad and ps.

Yes something like this has been on my todo list for a long time. But due to my full-time job, development on SquadMC has kind of stopped for a while now. Maybe with Squad A13 I'll get some motivation to update the maps and add new features to the app.

Regarding the meter spread: My idea is to show x/y lines or circles, indicating mortar impacts if bearing/azimuth is adjusted +/-1. Then I'd also add buttons to go +/-1 in each direction.

> I was looking at it and and realized that with your left and right round selector at the bottom it could also be nice if you had 30 rounds you could cycle through from 1 left once to 30 instead of going right from 1 all the way to the end. 1,2,3...30

Great suggestion, and should be easy enough to implement. Thanks for feedback!

> Thanks again, its an awesome utility, we use SquadCalc.com only when yours is not available for a new map.

Thank you :smile: 
 
> I'll make sure to get you these files as new maps come out. Would responding to this thread or making a new one each time be best?

A new thread for each map would be preferred, so I can keep track of which ones have been added already.

**Comment by tikityler** [comment]
Another option that could be easier to implement would be like how you use your area one now, but instead of populating each spot in between just show the two options.
If I set mortar markers on each side of the area I want to hit, on the bottom left and top right for example, if it showed both of those on the bottom I could know alright mortar 1 is as close as I should go and as left, and mortar 2 is as right and as far as I should go. 
Should be as simple as when using that method just show both mortar solutions and label them green and red or whatever colors used.

Either way thanks again and I totally understand getting busy with your job and stopping the side projects. 

> Regarding the meter spread: My idea is to show x/y lines or circles, indicating mortar impacts if bearing/azimuth is adjusted +/-1. Then I'd also add buttons to go +/-1 in each direction.


Squad A12 was an awesome update and I wish they would bring the fire team options over to PS. Anything major planned on A13?
