### ISSUE TITLE
Height difference

### ISSUE THREAD

**Issue by Endebert** [Endebert/squadmc#4]
Code related steps to get this feature completed:
- [x] create function to calculate elevation without the need of the mortar table
- [x] enhance function so that height difference is taken into consideration
- [x] load heightmap data
- [x] calculate height based on pixel value and scaling factor

The hard part is done, now all that is needed is the heightmaps for each level.

- [x] Al Basrah
- [x] Belaya
- [x] Chora Valley
- [x] Fool's Road
- [x] Operation First Light (Forest)
- [x] Gorodok
- [x] Jensen's Range
- [x] Kohat Toi River Valley
- [x] Kokan
- [x] Logar Valley
- [x] Mestia
- [x] Narva
- [x] Sumari Bala
- [x] Yehorivka

For each map, we need 4 things:
1. exported heightmap as 16bit PNG
2. Landscape Transform
   ![screenshot 3](https://user-images.githubusercontent.com/9431420/36593480-1f6128ce-189a-11e8-98b7-a2ce0bf489b0.png)
3. NW Minimap CornerMarker Transform
   ![screenshot 1](https://user-images.githubusercontent.com/9431420/36593473-1ccbd708-189a-11e8-80f9-5b37478caeee.png)
4. SE Minimap CornerMarker Transform
   ![screenshot 2](https://user-images.githubusercontent.com/9431420/36593476-1e186536-189a-11e8-8636-489de2758039.png)

With that information, I can double-check the map sizes and crop  the heightmap to fit the minimap.

**Comment by JamesLongman** [comment]
Looks good, good to see someone's working on tackling this problem

**Comment by Endebert** [comment]
At this moment, I have proper heightmaps for all maps except Al Basrah and Narva. My PC is not powerful enough to load those maps in the SquadSDK.

But this is good enough to get it onto the master branch. Will keep this issue open until I find someone who can help me with the last 2 maps.

BTW if anyone wants to try the same thing: the landscape transform does not always represent the NW origin of the exported heightmap, so keep that in mind. I went though all maps manually, placing actors in the north west corner of the landscapes, in order to get the correct origin. With that information, I can then calculate the offset I need to set in Photoshop, so that the minimap and heightmap overlap properly.

**Comment by Endebert** [comment]
Progress update:

Added the last two missing heightmaps. Even got the heightmap of the updated Kohat map exported.

Currently, only Kamdesh's heightmap is missing, as it doesn't load in the current SDK. Will be added once new SDK has been released. Luckily, the map doesn't have a very varied terrain.

- [ ] Kamdesh

**Comment by Endebert** [comment]
New SDK is out, heightmap + data for Kamdesh has been extracted. Closing this issue
