### ISSUE TITLE
New Map: Grave

### ISSUE THREAD

**Issue by tikityler** [Endebert/squadmc#43]
Map files https://drive.google.com/open?id=16JcAnxWAn0smkFdH-IXRR8p-SzAmEZ3k
![image](https://user-images.githubusercontent.com/15217704/58755418-ec8fed80-84a0-11e9-9050-863eee83af33.png)

Was there anything else you needed?

**Comment by Endebert** [comment]
Just added it to the map list. Thanks for the contribution!
