### ISSUE TITLE
Arnhem Range Update

### ISSUE THREAD

**Issue by tikityler** [Endebert/squadmc#44]
[Arnhem_Range.zip](https://github.com/Endebert/squadmc/files/3244351/Arnhem_Range.zip)
![image](https://user-images.githubusercontent.com/15217704/58755448-a8e9b380-84a1-11e9-8339-0caee9ede0bb.png)

**Comment by Endebert** [comment]
Hey, unfortunately the map (i.e. the tga file) you extracted from the assets is the old version, not the one that matches the ingame screenshot. Can you please check again, maybe the new version has a different name in the game files.

**Comment by tikityler** [comment]
Oh, sorry about that I'll do that as soon as I get an opportunity to.
Thanks again for your awesome tool and keeping it going

**Comment by tikityler** [comment]
[Arnhem_Range.zip](https://github.com/Endebert/squadmc/files/3263160/Arnhem_Range.zip)
Let me know if this looks right

**Comment by Endebert** [comment]
Yes, the new map are correct. Just pushed the update. Thanks for the contribution!
