### ISSUE TITLE
Area Attack

### ISSUE THREAD

**Issue by Katalam** [Endebert/squadmc#45]
I just found the project 20 min ago and shot some solutions. But is it possible to display all the area solution at the same time. When I have it open on the second monitor, the need to tab out every time is really time-consuming.
At the moment:
![atm](https://user-images.githubusercontent.com/39590058/61833595-13511b80-ae75-11e9-9e53-28cec5ab811a.png)
Maybe better:
![better](https://user-images.githubusercontent.com/39590058/61833597-151adf00-ae75-11e9-9539-4ae3a1b1342e.png)

**Comment by Endebert** [comment]
Personally I'd prefer to have them next to each other in the footer, and you'd cycle through "pages" or something like that.

The difficulty comes when trying to support both mobile and desktop users. I'd gladly merge any PR that comes up with a nice solution.
