### ISSUE TITLE
Severely needs update

### ISSUE THREAD

**Issue by tanksmontaje** [Endebert/squadmc#46]
We're in alpha 15 and many new features/map have been added. :) just a user love it on the maps (mestia brutal murder of crucible alpha) i can use it. Have no idea how to code.

**Comment by Endebert** [comment]
Hey, what exactly do you feel needs to be added/updated?

I'm still trying to find time to get back into the code, but recently I updated & added every map of the game: https://github.com/Endebert/squadmc-maps/issues/8

**Comment by tanksmontaje** [comment]
sorry :) hate to be a complainer. Just noticed skorpo was added to drop down. My bad for making this post. side note Canada update just came out and they added manic-5 and nanisivik to maps. Thank you for the updates and the work you do.
