### ISSUE TITLE
yehorivka

### ISSUE THREAD

**Issue by tanksmontaje** [Endebert/squadmc#47]
Grids are wrong. EX F06-5-5 in game map is E05-5-7 in calc map

**Comment by Endebert** [comment]
Thank you for pointing this out. I just fixed it. Sorry it took so long.

https://github.com/Endebert/squadmc-maps/commit/2343babfd8ab8167335dfe9d4110616b758ee802

**Comment by tanksmontaje** [comment]
No, thank you. Love this app. I'll try my best to spot any bugs and let you know (I use it alot)
