### ISSUE TITLE
New Mil Values in PS 4.21

### ISSUE THREAD

**Issue by thev21** [Endebert/squadmc#52]
Hello - It appears that the developers changed the mortar MIL values in a recent patch. So when using your (awesome!) tool it displays the incorrect MIL value. 

I took a screenshot of the new values in-game. 
**USA  6CM Mortars**
![USA6CM](https://user-images.githubusercontent.com/58535001/70190082-036b0300-16c3-11ea-8398-b99167dbb9cb.png)

**Brit 4"**
![Brit4](https://user-images.githubusercontent.com/58535001/70190083-036b0300-16c3-11ea-968e-f4e95460644c.png)
**Brit 3"**
![Brit3](https://user-images.githubusercontent.com/58535001/70190086-036b0300-16c3-11ea-9862-387a45309e5b.png)

**Ger 8CM"**
![Germ_8CM](https://user-images.githubusercontent.com/58535001/70190084-036b0300-16c3-11ea-9850-e0d315a54bca.png)

**Comment by tikityler** [comment]
Here it is in google sheet/excel if that will help
https://docs.google.com/spreadsheets/d/16d7BperDZJElnAqd34oB4uYNrdV0Zv-NUs0-REc1voY/edit?usp=sharing
[PSMC Assistant.xlsx](https://github.com/Endebert/squadmc/files/3991146/PSMC.Assistant.xlsx)

**Comment by tash** [comment]
This is not fixed. Brit 4" on Osterbeek still produces wrong/old values with 2.12.2

**Comment by Endebert** [comment]
@tash Please follow this issue regarding inaccurate mil calculation for PostScriptum: https://github.com/Endebert/squadmc/issues/61
