### ISSUE TITLE
New ranges in Post Scriptum

### ISSUE THREAD

**Issue by kura001** [Endebert/squadmc#61]
Hi Endebert. Your mortar calculator is really perfect!
We have new mortar ranges in Post Scriptum. And a new faction - the French. Fortunately, they use the same mortars as the British Faction. And two new maps Dinant and Stonne. So far I haven't been able to get you a high-resolution PNG of maps. New ranges:

const gerTable = [
  [100, 1536],
  [150, 1519],
  [200, 1502],
  [250, 1485],
  [300, 1467],
  [350, 1450],
  [400, 1432],
  [450, 1415],
  [500, 1397],
  [550, 1378],
  [600, 1360],
  [650, 1341],
  [700, 1322],
  [750, 1302],
  [800, 1282],
  [850, 1262],
  [900, 1241],
  [950, 1219],
  [1000, 1196],
  [1050, 1172],
  [1100, 1147],
  [1150, 1121],
  [1200, 1092],
  [1250, 1062],
  [1300, 1027],
  [1350, 988],
  [1400, 939],
];

const br4inchTable = [
  [200, 1535],
  [300, 1517],
  [400, 1500],
  [500, 1482],
  [600, 1464],
  [700, 1446],
  [800, 1428],
  [900, 1409],
  [1000, 1391],
  [1100, 1372],
  [1200, 1353],
  [1300, 1333],
  [1400, 1313],
  [1500, 1293],
  [1600, 1272],
  [1700, 1250],
  [1800, 1228],
  [1900, 1205],
  [2000, 1181],
  [2100, 1155],
  [2200, 1128],
  [2300, 1100],
  [2400, 1069],
  [2500, 1034],
];

const br3inchTable = [
  [100, 1536],
  [150, 1519],
  [200, 1502],
  [250, 1485],
  [300, 1467],
  [350, 1450],
  [400, 1432],
  [450, 1415],
  [500, 1397],
  [550, 1378],
  [600, 1360],
  [650, 1341],
  [700, 1322],
  [750, 1302],
  [800, 1282],
  [850, 1262],
  [900, 1241],
  [950, 1219],
  [1000, 1196],
  [1050, 1172],
  [1100, 1147],
  [1150, 1121],
  [1200, 1092],
  [1250, 1062],
  [1300, 1027],
  [1350, 988],
  [1400, 939],
];

const usa6cmTable = [
  [100, 1536],
  [150, 1519],
  [200, 1502],
  [250, 1485],
  [300, 1467],
  [350, 1450],
  [400, 1432],
  [450, 1415],
  [500, 1397],
  [550, 1378],
  [600, 1360],
  [650, 1341],
  [700, 1322],
  [750, 1302],
  [800, 1282],
  [850, 1262],
  [900, 1241],
  [950, 1219],
  [1000, 1196],
  [1050, 1172],
  [1100, 1147],
  [1150, 1121],
  [1200, 1092],
  [1250, 1062],
  [1300, 1027],
  [1350, 988],
  [1400, 939],
];

**Comment by kura001** [comment]
high-resolution PNGs:
https://drive.google.com/open?id=10QegHdy9gThO_M0JfvZ1k3GCqCdKTqCl

**Comment by Endebert** [comment]
@kura001 thanks for all the info! Is it possible to also make a screenshot of the new maps in game? I need the ingame grid to estimate the map sizes.

**Comment by kura001** [comment]
Somebody really should buy you the game... :) Ingame screens with grid:
https://drive.google.com/open?id=1rv9hMf19_uMlOt010mtE9O918wJg0U_F

I still have an idea for functionality. Could we see the impact spread? As another circle, it would depend on the type of mortar.

**Comment by kura001** [comment]
Hi again, there is something wrong with calculating mills. I compared what your app counts on and what distances are in the game. 
Ger 8cm: 500m 
PSMC: 1410.9 
Ingame range: [500, 1397], 
BRIT 4″: 500m 
PSMC: 1502.7 
Ingame range: [500, 1482], 
BRIT 3″: 500m 
PSMC: 1410.9 
Ingame range: [500, 1397], 
US M49A2: 500m 
PSMC: 1410.9 
Ingame range: [500, 1397], 
It looks, according to the screens, that German 8cm, British 3 ″, American are same type of mortars. The other numbers has only the British 4 ″ (French 4).
I tested ingame mils - Ger 8cm, BRIT 4 ″, BRIT 3 ″ and the tables in the game are accurate.

Mortar tables screens:
https://drive.google.com/open?id=1O_Dnj24NyRRp1CFzg7e3rPoaIyiQxP16

**Comment by Endebert** [comment]
@kura001 I noticed as much when generating the new velocity based on your data. It seems mortars work a bit differently in PS than they do in Squad. Here's an example output from my calculation:

```
GER: FINAL VELOCITY     : 116.179939
GER: FINAL AVG DEVIATION: -0.0000022
GER: FINAL MAX RANGE    : 1377.32
GER: ===============================================
GER: Generating overview...
GER: ===============================================
GER:  DIST  T-MIL  |   F-MIL   |   DEV   |    VEL
GER: --------------|-----------|---------|----------
GER: 0100m 1536mil | 1563.0mil | d=-26.99 | v=88.426
GER: 0150m 1519mil | 1544.4mil | d=-25.42 | v=96.342
GER: 0200m 1502mil | 1525.8mil | d=-23.78 | v=101.238
GER: 0250m 1485mil | 1507.0mil | d=-22.04 | v=104.609
GER: 0300m 1467mil | 1488.2mil | d=-21.17 | v=106.710
GER: 0350m 1450mil | 1469.1mil | d=-19.14 | v=108.701
GER: 0400m 1432mil | 1449.9mil | d=-17.93 | v=110.008
GER: 0450m 1415mil | 1430.5mil | d=-15.49 | v=111.408
GER: 0500m 1397mil | 1410.8mil | d=-13.79 | v=112.361
GER: 0550m 1378mil | 1390.8mil | d=-12.79 | v=112.986
GER: 0600m 1360mil | 1370.4mil | d=-10.44 | v=113.806
GER: 0650m 1341mil | 1349.7mil | d=-08.69 | v=114.379
GER: 0700m 1322mil | 1328.5mil | d=-06.48 | v=114.952
GER: 0750m 1302mil | 1306.7mil | d=-04.73 | v=115.360
GER: 0800m 1282mil | 1284.4mil | d=-02.36 | v=115.805
GER: 0850m 1262mil | 1261.3mil | d=+00.73 | v=116.287
GER: 0900m 1241mil | 1237.3mil | d=+03.68 | v=116.671
GER: 0950m 1219mil | 1212.4mil | d=+06.64 | v=116.989
GER: 1000m 1196mil | 1186.2mil | d=+09.83 | v=117.268
GER: 1050m 1172mil | 1158.5mil | d=+13.53 | v=117.533
GER: 1100m 1147mil | 1128.9mil | d=+18.12 | v=117.808
GER: 1150m 1121mil | 1096.8mil | d=+24.21 | v=118.112
GER: 1200m 1092mil | 1061.3mil | d=+30.71 | v=118.315
GER: 1250m 1062mil | 1020.7mil | d=+41.29 | v=118.622
GER: 1300m 1027mil | 0971.5mil | d=+55.53 | v=118.825
GER: 1350m 0988mil | 0901.6mil | d=+86.38 | v=119.103
GER: 1400m 0939mil | 000NaNmil | d=+00NaN | v=119.362
```

You can see from that final console output, that the projectile velocity seems to be increasing by distance in order for the ingame mortar table to be correct. This is true for all PS mortars, while the squad mortar has a constant projectile velocity. In fact, my calculations are based on that assumption.

In order to counter-act this, I try to calculate the average velocity that is overall closest to the table values. In the console output above, `d` is the deviation from the table mil to the calculated mil. As I said, the calculations in squadmc are based on one velocity, so the calculations are most accurate at mid-range. Unfortunately this also means that at close/long range, the squadmc values can be quite a bit off, over 50m at long range it seems.

Would be great if anyone could test the mortar tables ingame and check them for accuracy. Either PS mortars work differently to squad, or the ingame tables are faulty.

If ps does mortars differently, I guess I either have to come up with a new algorithm for it, or go the old school way and just interpolate between table values. This was not possible previously, as I remember most of the range of e.g. the 4 inch mortar was not covered by the ingame table in the past.

**Comment by kura001** [comment]
It looks like mortar tables in the game shoot accurately.
I test even later if there are any inaccuracies, I will inform you.
One very good person gave me extra mills that work outside the ingame tables. Included below:

Ger 8cm, BRIT 3″, US M49A2
300, 1467
350, 1450
400, 1432
450, 1415
500, 1397
550, 1378
600, 1360
650, 1341
700, 1322
750, 1302
800, 1282
850, 1262
900, 1241
950, 1219
1000, 1196
1050, 1172
1100, 1147
1150, 1121
1200, 1092
1250, 1062
1300, 1027
1350, 988
1400, 939
extra
1436, 890
1460, 850
1469, 800
1471, 770

BRIT 4″
600, 1464
700, 1446
800, 1428
900, 1409
1000, 1391
1100, 1372
1200, 1353
1300, 1333
1400, 1313
1500, 1293
1600, 1272
1700, 1250
1800, 1228
1900, 1205
2000, 1181
2100, 1155
2200, 1128
2300, 1100
2400, 1069
2500, 1034
extra
2600, 999
2670, 964
2730, 929
2780, 894
2815, 859
2832, 824
2842, 800

**Comment by kura001** [comment]
https://mega.nz/#!JQVmyaLC!lUgxp5EiWcAJS_7c7kW5KfDfLvsvWYz1USxplw-Pliw

po 20. 1. 2020 o 8:40 Robert Ende <notifications@github.com> napísal(a):

**Comment by Endebert** [comment]
Do you know by chance how that person got those values? Can they be extracted from the game files or SDK? Might be interesting for squad as well...

Of course, if you can give me the extra ranges for all mortars, I'll add the table interpolation method for postscriptum

**Comment by kura001** [comment]
From what he wrote to me, just from personal testing right ingame. He set the mills and where it fell, he measured the distance. He has his own custom calculator converted to PS from http://squad.ujkl.ru/

I'd like to use his calculator, but only yours works well under Android. So I look forward to when you fix yours and add new maps. :)

**Comment by Endebert** [comment]
Please let me know if this is still relevant. We figured out that the degree to milliradian conversion might be off for post scriptum, which might solved the issue: https://github.com/Endebert/squadmc/pull/80

**Comment by Endebert** [comment]
Closing this for now until someone says it's still off. I don't own the game, so I can't check it myself.
