### ISSUE TITLE
Switch over to 'squadmc.app'

### ISSUE THREAD

**Issue by Trikolon** [Endebert/squadmc#64]
Switch over to https://squadmc.app, https://psmc.squadmc.pro/ and redirect old urls via HTTP 301.

**Comment by Walldo** [comment]
Website is loading, but I'm just getting a constant load screen 
<img width="449" alt="Screen Shot 2020-01-25 at 7 45 48 PM" src="https://user-images.githubusercontent.com/556432/73129159-4e124880-3fab-11ea-9a17-1389532398ea.png">

**Comment by hypoxia125** [comment]
Can verify that there is a perpetual loading screen, even with NodeJS installed.
