### ISSUE TITLE
PostScriptumMC incorrect

### ISSUE THREAD

**Issue by spieli1960** [Endebert/squadmc#76]
On the 3rd December 2019 the Mortar system in Post Scriptum was changed and the calculator is now inaccurate and uses the old values
Example:
PS: 100m 1536mil - PSMC: 100m 1563mil
PS: 1000m 1196mil - PSMC: 1000m 1186mil

I'm not sure what changed but to quote the patchnotes:
"Fixed mortar aim being off by 100-200 meters."
The Calculator worked fine before this change however.

I looked inside the MortarCalc Code and found out that the new values are already in place, yet it displays the old values.
I would be ready to help with as much research as needed within the limits of the Game, however I'm not much of a Coder or Mathematician.

**Comment by spieli1960** [comment]
Sidenote: My theory would be that maybe changing the milF to 360/6300 instead of 360/6400 could maybe help solve the issue, but again that's nothing but a guess.

**Comment by ansarto** [comment]
I just did the math, and in fact there are 2 issues

- The first one is, as you said, a bad approximation of pi
- The second one is wrong initial speed values

I propose these values for the /src/assets/Vars.js file
[Vars.zip](https://github.com/Endebert/squadmc/files/4956408/Vars.zip)

export const PS_8CM_NAME = "GER 8cm";
export const PS_8CM_VELOCITY = **119.93**;
export const PS_8CM_MAX_DISTANCE = **1467**;

export const PS_3INCH_NAME = "BRIT 3″";
export const PS_3INCH_VELOCITY = **119.93**;
export const PS_3INCH_MAX_DISTANCE = **1467**;

export const PS_4INCH_NAME = "BRIT 4″";
export const PS_4INCH_VELOCITY = **166.94**;
export const PS_4INCH_MAX_DISTANCE = **2818**;

export const PS_6CM_NAME = "US 6cm";
export const PS_6CM_VELOCITY = **119.93**;
export const PS_6CM_MAX_DISTANCE = **1467**;

export const GRAVITY = 9.8;
export const MIL_TO_DEG_FACTOR = **360.0 / 6283.1853**;
export const MAX_SUBTARGETS_COUNT = 49;

**Comment by spieli1960** [comment]
Excellent.
But how did you get this information? What's the math you did?

**Comment by flogie** [comment]
I did some testing and it seems it fixes the issues with the calculator on Post Scriptum.

Can someone release that into the current version?

**Comment by ansarto** [comment]
> Excellent.
> But how did you get this information? What's the math you did?
> 
> Either way, I of course thank you for everything.

I did the math by dichotomy.

Comparing my values with the ones in the game, I only have +~- 2 milliradians of differences

**Comment by Endebert** [comment]
Should be fixed now. @ansarto was nice enough to update the mortar velocities here: https://github.com/Endebert/squadmc/pull/80

and I pushed a fix to switch the milliradian conversion factor based on the game, see here: https://github.com/Endebert/squadmc/pull/83
