### ISSUE TITLE
Fallujah

### ISSUE THREAD

**Issue by mattymice** [Endebert/squadmc#92]
Hey Fallujah was just added when v1 dropped any chance we can get it added into the calc before OISC starts, since OWI plans on showcasing it during the tournament. Thanks in advance.

**Comment by Endebert** [comment]
Is fallujah already included in the SDK? Otherwise we'll have to wait.

One alternative would be if someone could provide me with a high-res screenshot of the fully zoomed out map in game. Preferably like 8k or something. Then I can add it without a heightmap

**Comment by LukeThorp** [comment]
This has now been added @mattymice , you are welcome.

**Comment by LukeThorp** [comment]
@Endebert you can close this issue

**Comment by Endebert** [comment]
Corresponding PR: https://github.com/Endebert/squadmc-maps/pull/26

Thanks again @LukeThorp for the contribution.
